repertoire/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'repertoire'

urlpatterns = [
    url(r'^$', views.ElementList.as_view(), name='list_oeuvres'),
    url(r'^zotero$', views.zotero_list, name='synchro_zotero'),
    url(r'new/$', views.ElementNew.as_view(), name='new_oeuvre'),
    url(r'^(?P<pk>.+)/$', views.ElementDisplay.as_view(), name='display_oeuvre'),
    url(r'^(?P<pk>.+)/edit$', views.ElementEdit.as_view(), name='edit_oeuvre'),
]

repertoire_udm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home_view, logout_view
from repertoire import views

urlpatterns = [
        url(r'^$', views.ElementList.as_view(), name='home'),
        url(r'^logout$', logout_view, name='logout'),
        url(r'^admin/', admin.site.urls),
        url(r'^search/', include('haystack.urls')),
        url(r'^', include('repertoire.urls')),
]

repertoire/models.py
from django.db import models
import tagulous.models

# Create your models here.
class TagAuteur(tagulous.models.TagModel):
    class TagMeta:
        pass

class TagLang(tagulous.models.TagModel):
    class TagMeta:
        pass

class Oeuvre(models.Model):
    titre = models.CharField(max_length=200, null=True, blank=False)
    auteur = models.CharField(max_length=200, null=True, blank=True)
    #auteur = tagulous.models.TagField(to=TagAuteur)
    url = models.URLField(max_length=200, null=True, blank=True)
    lieu = models.CharField(max_length=200, null=True, blank=True)
    langue = tagulous.models.TagField(to=TagLang)
    id_zotero = models.CharField(max_length=200, db_index=True, unique=True, blank=True, null=True)

    def __str__(self):
        return self.titre + ' ' + self.id_zotero

repertoire/forms.py
from django.forms import ModelForm
from .models import Oeuvre

class ELementForm(ModelForm):
    class Meta:
        model = Oeuvre
        fields = [ 'titre', 'auteur', ]

repertoire/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .zotero import MyZotero

from .models import Oeuvre


def zotero_list(request):
    zot = MyZotero()
    zot.create_from_zotero_top(10)

    return redirect('repertoire:list_oeuvres')

class ElementList(ListView):
    model = Oeuvre
    context_object_name = 'oeuvres'
    template_name = 'oeuvres/list_page.html'


class ElementDisplay(DetailView):
    model = Oeuvre
    context_object_name = 'oeuvre'
    template_name = 'oeuvres/display.html'


class ElementEdit(UpdateView):
    model = Oeuvre
    fields = [ 'title', 'articles' ]
    template_name = 'oeuvres/edit.html'

    def get_success_url(self):
        return reverse('sp_app:display_oeuvre', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        if self.request.user.has_perm('sp_app.change_element'):
            return super(ElementEdit, self).form_valid(form)
        else:
            return HttpResponseForbidden()

# Class based view, form
class ElementNew(CreateView):
    model = Oeuvre
    fields = [ 'title', 'articles' ]
    template_name = 'oeuvres/edit.html'

    def get_success_url(self):
        return reverse_lazy('sp_app:display_oeuvre', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        if self.request.user.has_perm('sp_app.add_element'):
            form.instance.creator = self.request.user
            return super(ElementNew, self).form_valid(form)
        else:
            return HttpResponseForbidden()

repertoire_udm/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from repertoire import models

def logout_view(request):
    logout(request)
    return redirect('home')

def home_view(request):
    oeuvres = models.Oeuvre.objects.all()

    return render(request, 'core/home.html',
        { 'oeuvres': oeuvres }
    )

templates/core/base.html
{% load bootstrap3 %}
{% load static %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Répertoire</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="Tim">

  {% load staticfiles %}
  {% block css %}
  {% endblock %}

  {% bootstrap_css %}

  <link rel="stylesheet" href="{% static "css/styles.css" %}">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  {% block js %}
  {% endblock %}

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>

<body>
    {% include "core/navigation.html" %}
    {% bootstrap_messages %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script type="text/javascript" src="//code.jquery.com/jquery-3.2.1.min.js"></script>
    {% bootstrap_javascript %}
</body>
</html>

templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
<h2>{{ Oeuvre.titre }}</h2>
{% endblock %}

templates/core/navigation.html
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                Répertoire
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'repertoire:list_oeuvres' %}">Oeuvres</a></li>
                <li><a href="{% url 'repertoire:synchro_zotero' %}">Synchro Zotero</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="padding-right: 40px;">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}"><i class="fa fa-power-off" aria-hidden="true"></i> Logout</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% if user.is_authenticated %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar2" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                Actions
            </a>
        </div>
        <div id="navbar2" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                    <li><a href="{% url 'repertoire:new_oeuvre' %}"><i class="fa fa-plus-square" aria-hidden="true"></i> Oeuvre</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endif %}

templates/oeuvres/display.html
{% extends 'core/base.html' %}

{% block content %}
<h2>{{ oeuvre.titre }}</h2>
<ul>
    <li>{{ oeuvre.url }}</li>
    <li>{{ oeuvre.auteur }}</li>
    <li>{{ oeuvre.id_zotero }}</li>
</ul>
{% endblock %}

templates/oeuvres/list_page.html
{% extends 'core/base.html' %}

{% block content %}
<h2>Liste</h2>
<ul>
    {% for item in oeuvres %}
    <li><a href="{% url 'repertoire:display_oeuvre' item.pk %}">{{ item.titre }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

templates/oeuvres/zotero_list.html
{% extends 'core/base.html' %}

{% block content %}
<h2>Zotero</h2>
{% for item in oeuvres %}
<pre style="white-space: pre-wrap;">{{ item }}</pre>
<pre>
    {{ item.data.key }}
    {{ item.data.title }}
    {{ item.data.url }}
    {% for creator in item.data.creators %}
    {{ creator.firstName }} {{ creator.lastName }}
    {% endfor %}
</pre>
{% endfor %}
{% endblock %}

templates/search/search.html
{% extends 'core/base.html' %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.titre }} {{result.object.id_zotero}} {{result.object.pk}}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}